### ISSUE TITLE
 assembler cannot create object files

### ISSUE THREAD

**Issue by majabee** [imagemin/jpegtran-bin#78]
I have these installation problems with jpegtran-bin@3.2.0, 
```
jpegtran-bin@3.2.0 postinstall /Users/xx/yy/sites/projects/gulptest/node_modules/jpegtran-bin
> node lib/install.js

  ⚠ Couldn't execute the `/Users/xx/yy/sites/projects/gulptest/node_modules/jpegtran-bin/vendor/jpegtran` binary. Make sure it has the right permissions.
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ Error: touch configure.ac aclocal.m4 configure Makefile.am Makefile.in && ./configure --disable-shared --prefix="/Users/xx/yy/sites/projects/gulptest/node_modules/jpegtran-bin/vendor" --bindir="/Users/xx/yy/sites/projects/gulptest/node_modules/jpegtran-bin/vendor" && make install
Command failed: ./configure --disable-shared --prefix="/Users/xx/yy/sites/projects/gulptest/node_modules/jpegtran-bin/vendor" --bindir="/Users/xx/yy/sites/projects/gulptest/node_modules/jpegtran-bin/vendor"
configure: error: installation or configuration problem: assembler cannot create object files.

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```
What can I do?

**Comment by shinnn** [comment]
Install NASM. http://www.nasm.us/

**Comment by fengerzh** [comment]
`brew install nasm`
