### ISSUE TITLE
executable perm not set pm installed jpegtran-bin/vendor/jpegtran binary

### ISSUE THREAD

**Issue by pgnd** [imagemin/jpegtran-bin#82]
With prereqs installed

```
yarn add --dev \
 bin-build@^3.0 \
 jpegtran-bin@^3.0
```

attempt to install jpegtran

```
yarn add --dev jpegtran@^1.0
```

fails

```
yarn add v0.24.6
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⠐ jpegtran-bin:   ℹ compiling from source
[-/1] ⠐ waiting...
[-/1] ⠐ waiting...
[-/1] ⠐ waiting...
error /test/node_modules/jpegtran/node_modules/jpegtran-bin: Command failed.
Exit code: 1
Command: sh
Arguments: -c node lib/install.js
Directory: /test/node_modules/jpegtran/node_modules/jpegtran-bin
Output:
⚠ Couldn't execute the `/test/node_modules/jpegtran/node_modules/jpegtran-bin/vendor/jpegtran` binary. Make sure it has the right permissions.
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1167:7)
    at mkdirp (/test/node_modules/fs-mkdirp-stream/mkdirp.js:17:18)
    at onDirpath (/test/node_modules/fs-mkdirp-stream/index.js:31:9)
    at dirpath (/test/node_modules/vinyl-fs/lib/dest/index.js:26:5)
    at DestroyableTransform.makeFileDirs [as _transform] (/test/node_modules/fs-mkdirp-stream/index.js:24:7)
    at DestroyableTransform.Transform._read (/test/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/test/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/test/node_modules/readable-stream/lib/_stream_writable.js:405:64)
    at writeOrBuffer (/test/node_modules/readable-stream/lib/_stream_writable.js:394:5)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

checking perms

```
ls -al /test/node_modules/jpegtran/node_modules/jpegtran-bin/vendor/
	total 308K
	drwxr-x---+ 2 root root 4.0K Jun 26 09:49 ./
	drwxr-x---+ 5 root root 4.0K Jun 26 09:49 ../
	-rw-rw----+ 1 root root 299K Jun 26 09:49 jpegtran
```

fixing perms

```
chmod +x /test/node_modules/jpegtran/node_modules/jpegtran-bin/vendor/jpegtran
```

now install works

```
yarn add --dev jpegtran@^1.0

	yarn add v0.24.6
	[1/4] Resolving packages...
	[2/4] Fetching packages...
	[3/4] Linking dependencies...
	[4/4] Building fresh packages...
	success Saved lockfile.
	success Saved 4 new dependencies.
	├─ is-absolute@0.1.7
	├─ jpegtran@1.0.5
	├─ memoizeasync@0.9.0
	└─ passerror@1.1.1
	Done in 4.86s.
```

**Comment by shinnn** [comment]
> ```
> jpegtran@^1.0
> ```

That's extremely older version. Use the latest one.

**Comment by pgnd** [comment]
@shinnn 

> That's extremely older version. Use the latest one.

The latest version of jpegtran **IS** v1.0.5 (https://www.npmjs.com/package/jpegtran)

and that's exactly what's installed

```
yarn list | grep jpegtran
├─ jpegtran-bin@3.2.0
├─ jpegtran@1.0.5
│  ├─ jpegtran-bin@=3.0.4
│  ├─ jpegtran-bin@3.0.4
```

**Comment by shinnn** [comment]
Ah, so you posted this issue on the wrong repo.

This package is jpegtran<b>-bin</b>.

**Comment by pgnd** [comment]
@shinnn 

> Ah, so you posted this issue on the wrong repo.

No.

Ss I posted above, it's the incorrect/unset executable permission on the jpegtran-**bin** binary that's causing the problem

**Comment by shinnn** [comment]
I can successfully install jpegtran-bin@3.2.0 with both npm and Yarn. Probably the permission problem you encountered is not caused by this module but the others.

If you want us to investigate further,

1. Create a small public repository
2. Set up CI for it, for exmaple Travis CI and CircleCI
3. Let the build fail
4. Show us the link to the failing build log

**Comment by pgnd** [comment]
As I stated above,  I do not have a problem installing jpegtran-**bin**.

It's installed, with the executable bit not set on the binary.

Never mind.

**Comment by shinnn** [comment]
"can successfully install" means that the file is completely downloaded and it has desired execute permission.

```
$ /bin/ls -al node_modules/jpegtran-bin/vendor/jpegtran
-rwxr-xr-x  1 Shinnosuke  staff  308140  6 27 02:23 node_modules/jpegtran-bin/vendor/jpegtran
```
